name: Snyk Code + Open Source Scan

on:
  workflow_dispatch:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  snyk-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Verify Snyk CLI version
        run: snyk --version
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Install project dependencies
        run: npm install

      # --- Snyk Code (SAST) Scan ---
      - name: Run Snyk Code scan
        run: snyk code test --severity-threshold=medium
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # --- Snyk Open Source (SCA) Scan ---
      - name: Run Snyk Open Source scan
        run: snyk test --all-projects --severity-threshold=medium
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # --- Upload SARIF Results to GitHub Security tab (Snyk Code only) ---
      - name: Upload Snyk Code SARIF to GitHub Security tab
        if: always()  # ensures upload runs even if previous step fails
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif
